// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by XMeshSaver.rc
//
#define IDD_MESHCACHE 9
#define IDD_LICENSEFINDER 10
#define IDD_LICENSECONFIG 11
#define IDD_EDITLICENSE 12
#define IDC_STORE_VELOCITY 3076
#define IDC_VELOCITY_CHANNEL 3077
#define IDC_VELOCITY_EDIT 3077
#define IDC_VELOCITY_SPINNER 3078
#define IDC_CLAMP_EDIT 3079
#define IDC_CLAMP_SPINNER 3080
#define IDC_THRESH_EDIT 3081
#define IDC_THRESH_SPINNER 3082
#define IDC_LICENSEFINDER_CONTENTFRAME 3083
#define IDC_STATIC_REASON 3084
#define IDC_RADIO_SERVER 3085
#define IDC_RADIO_FILE 3086
#define IDC_EDIT_SERVERNAME 3087
#define IDC_CHECK_USESERVERPORT 3088
#define IDC_EDIT_SERVERPORT 3089
#define IDC_SPIN_SERVERPORT 3090
#define IDC_EDIT_FILEPATH 3091
#define IDC_BUTTON_FILEBROWSE 3092
#define IDC_DETAILS 3093
#define IDC_LISTBOX 3094
#define IDC_ADD 3095
#define IDC_EDIT 3096
#define IDC_REMOVE 3097
#define IDC_STATIC_SERVERNAME 3098

#define IDS_MESHCACHE 30265
#define IDS_STORE_VELOCITY 30266
#define IDS_VELOCITY_CHANNEL 30267
#define IDS_VELOCITY_CLAMP 30268
#define IDS_THRESHOLD 30269
#define IDS_MESHCACHE_CLASS 30277
#define IDS_MESHCACHEOBJECT 30278
#define IDC_STATIC -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 184
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 3099
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
